# Generated by Django 3.1.3 on 2020-11-04 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_or_debit', models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], default='debit', max_length=20)),
                ('particulars', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbook.ledgermaster')),
            ],
        ),
        migrations.CreateModel(
            name='DayBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_or_debit', models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], default='debit', max_length=20)),
                ('bank_or_cash', models.CharField(choices=[('cash', 'cash'), ('bank', 'bank')], default='cash', max_length=20)),
                ('particulars', models.CharField(default=False, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True)),
                ('ledger_master', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cashbook.ledgermaster')),
            ],
        ),
        migrations.CreateModel(
            name='CashBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulars', models.CharField(default=False, max_length=255)),
                ('credit_or_debit', models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], default='debit', max_length=20)),
                ('bank_or_cash', models.CharField(choices=[('cash', 'cash'), ('bank', 'bank')], default='cash', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbook.daybook')),
            ],
        ),
    ]
