# Generated by Django 3.1.2 on 2020-10-29 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='ledger_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ledger', to='cashbook.ledgermaster'),
        ),
    ]
