# Generated by Django 3.1.2 on 2020-10-29 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0002_auto_20201029_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybook',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='ledger_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ledger', to='cashbook.ledgermaster'),
        ),
    ]
